# Whenever you build a custom image, you will always base from someone else's image
FROM nginx

# Copy EVERYTHING in this (current) directory and paste it into `/usr/share/nginx/html`
COPY . /usr/share/nginx/html
